---
message: "This node is using hieradata from /hieradata/nodes/dev.yaml."
#The Dangerous Experimental Void node.
########################
#INCLUDE COMMON CLASSES#
########################
classes:
    - 'profile::dev'
    - 'beluga::params'
    - 'beluga::mysql_server'
    - 'beluga::apache_frontend_server'
    - 'beluga::drush_server'
    - 'nginx'
    - 'beluga::java'
    - 'jenkins'
    - 'docker'

#Docker configuration. Images can be found at https://registry.hub.docker.com/search?q=library
docker::service_name: 'docker'
docker::tcp_bind: 'tcp://127.0.0.1:4243'
docker::socket_bind: 'unix:///var/run/docker.sock'
docker::images:
    debian:
        image_tag: '8.1'
docker::run_instance:
    helloworld:
        image: 'debian:8.1'
        command: '/bin/sh -c "while true; do echo hello world; sleep 1; done"'

#Jenkins plugin hash is set here instead of in the jenkins module hieradata directory.
jenkins::plugins:
    'job-import-plugin':
        source: "https://updates.jenkins-ci.org/download/plugins/job-import-plugin/1.2/job-import-plugin.hpi"
    'git':
        source: 'https://updates.jenkins-ci.org/download/plugins/git/2.3.5/git.hpi'
    'scm-api':
        source: 'http://updates.jenkins-ci.org/download/plugins/scm-api/0.2/scm-api.hpi'
    'credentials':
        source: 'http://updates.jenkins-ci.org/download/plugins/credentials/1.22/credentials.hpi'
    'git-client':
        source: 'https://updates.jenkins-ci.org/download/plugins/git-client/1.17.1/git-client.hpi'
    'publish-over-ssh':
        source : 'https://updates.jenkins-ci.org/download/plugins/publish-over-ssh/1.12/publish-over-ssh.hpi'

beluga::drupal_sites:
   dev.silex-puppet-control.example:
       # silex-consulting.com drupal 7 site
       site_owner: jenkins
       db_user: sc
       db_name: sc_drupal
       docroot: /var/www/drupal/dev.silex-puppet-control.example/current/
       web_user: www-data
       web_group: www-data
       use_make_file: false
       #The functionalality to build drupal with a drush make file is still in development.
       #make_file_location: /vagrant/silex-drupal-7_distribution/distro.make
       site_aliases:
              - "dev.silex-puppet-control.example"
