---
#The VPS server hosts multiple drupal site which we define here.
message: "This node is using  hieradata from /hieradata/nodes/dev.radnetwork.co.uk.yaml."
########################
#INCLUDE COMMON CLASSES#
########################
classes:
    - 'beluga::params'
    - 'beluga::mysql_server'
    - 'beluga::apache_frontend_server'
    - 'beluga::drush_server'
    - 'nginx'
    - 'beluga::java'
    - 'jenkins'

#Jenkins plugin hash is set here instead of in the jenkins module hieradata directory.
jenkins::plugins:
    'job-import-plugin':
        source: "https://updates.jenkins-ci.org/download/plugins/job-import-plugin/1.2/job-import-plugin.hpi"
    'git':
        source: 'https://updates.jenkins-ci.org/download/plugins/git/2.3.5/git.hpi'
    'scm-api':
        source: 'http://updates.jenkins-ci.org/download/plugins/scm-api/0.2/scm-api.hpi'
    'credentials':
        source: 'http://updates.jenkins-ci.org/download/plugins/credentials/1.22/credentials.hpi'
    'git-client':
        source: 'https://updates.jenkins-ci.org/download/plugins/git-client/1.17.1/git-client.hpi'
    'publish-over-ssh':
        source : 'https://updates.jenkins-ci.org/download/plugins/publish-over-ssh/1.12/publish-over-ssh.hpi'

#Beluga Drupal development sites.
beluga::drupal_sites:
   silex-consulting.com:
       # silex-consulting.com drupal 7 site
       site_owner: jenkins
       db_user: sc
       db_name: sc_drupal
       docroot: /var/www/drupal/silex-consulting.com/current/
       web_user: www-data
       web_group: www-data
       use_make_file: false
       #The functionalality to build drupal with a drush make file is still in development.
       #make_file_location: /vagrant/silex-drupal-7_distribution/distro.make
       site_aliases:
              - "www.silex-consulting.com"

   silexresources.co.uk:
        # silexresources.co.uk drupal 7 site
       site_owner: jenkins
       db_user: sr
       db_name: sr_drupal
       docroot: /var/www/drupal/silexresources.co.uk/current/
       web_user: www-data
       web_group: www-data
       use_make_file: false
       #The functionalality to build drupal with a drush make file is still in development.
       #make_file_location: /vagrant/silex-drupal-7_distribution/distro.make
       site_aliases:
              - "www.silexresources.co.uk"

   westproperty.co.zw:
        # westproperty.co.zw drupal 7 site
       site_owner: jenkins
       db_user: wp
       db_name: wp_drupal
       docroot: /var/www/drupal/westproperty.co.zw/current/
       web_user: www-data
       web_group: www-data
       use_make_file: false
       #The functionalality to build drupal with a drush make file is still in development.
       #make_file_location: /vagrant/silex-drupal-7_distribution/distro.make
       site_aliases:
              - "www.westproperty.co.zw"

   westgroup.co.zw:
        # westgroup.co.zw drupal 7 site
       site_owner: jenkins
       db_user: wg
       db_name: wg_drupal
       docroot: /var/www/drupal/westgroup.co.zw/current/
       web_user: www-data
       web_group: www-data
       use_make_file: false
       #The functionalality to build drupal with a drush make file is still in development.
       #make_file_location: /vagrant/silex-drupal-7_distribution/distro.make
       site_aliases:
              - "www.westgroup.co.zw"

