#The web server role hosts multiple drupal site which we define here.
message: "This node is using  hieradata from modules/beluga/webserver.yaml."
beluga::drupal_sites:
   silex-puppet-control.example:
       #silex-puppet-control.example site
       site_owner: jenkins
       db_user: sc
       db_name: sc_drupal
       docroot: /var/www/drupal/silex-puppet-control.example/current/
       web_user: www-data
       web_group: www-data
       use_make_file: false
       #The functionalality to build drupal with a drush make file is still in development.
       #make_file_location: /vagrant/silex-drupal-7_distribution/distro.make
       site_aliases:
              - "www.silex-puppet-control.example"
